/** Shared permission definitions. Keep this module independent of Next.js and sessions. */
import type { Role } from '@/generated/prisma/client';

export const PERMISSIONS = {
    POSTS_CREATE: 'posts.create',
    POSTS_EDIT: 'posts.edit',
    POSTS_DELETE: 'posts.delete',
    POSTS_PUBLISH: 'posts.publish',
    POSTS_SCHEDULE: 'posts.schedule',
    ANALYTICS_VIEW: 'analytics.view',
    ANALYTICS_EXPORT: 'analytics.export',
    ANALYTICS_REPORTS: 'analytics.reports',
    TEAM_VIEW: 'team.view',
    TEAM_INVITE: 'team.invite',
    TEAM_MANAGE: 'team.manage',
    TEAM_REMOVE: 'team.remove',
    SETTINGS_VIEW: 'settings.view',
    SETTINGS_EDIT: 'settings.edit',
    SETTINGS_BILLING: 'settings.billing',
    ACCOUNTS_VIEW: 'accounts.view',
    ACCOUNTS_CONNECT: 'accounts.connect',
    ACCOUNTS_DISCONNECT: 'accounts.disconnect',
    MEDIA_VIEW: 'media.view',
    MEDIA_UPLOAD: 'media.upload',
    MEDIA_DELETE: 'media.delete',
    AUTOMATIONS_VIEW: 'automations.view',
    AUTOMATIONS_MANAGE: 'automations.manage',
    VIDEO_VIEW: 'video.view',
    VIDEO_CREATE: 'video.create',
    VIDEO_RENDER: 'video.render',
    DISCOVERY_VIEW: 'discovery.view',
    DISCOVERY_MANAGE: 'discovery.manage',
} as const;

export type PermissionCode = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

/** Built-in role grants; custom roles use the Permission/RolePermission tables. */
export const DEFAULT_ROLE_PERMISSIONS: Record<Exclude<Role, 'CUSTOM'>, PermissionCode[]> = {
    OWNER: Object.values(PERMISSIONS),
    ADMIN: [
        PERMISSIONS.POSTS_CREATE,
        PERMISSIONS.POSTS_EDIT,
        PERMISSIONS.POSTS_DELETE,
        PERMISSIONS.POSTS_PUBLISH,
        PERMISSIONS.POSTS_SCHEDULE,
        PERMISSIONS.ANALYTICS_VIEW,
        PERMISSIONS.ANALYTICS_EXPORT,
        PERMISSIONS.ANALYTICS_REPORTS,
        PERMISSIONS.TEAM_VIEW,
        PERMISSIONS.TEAM_INVITE,
        PERMISSIONS.TEAM_MANAGE,
        PERMISSIONS.SETTINGS_VIEW,
        PERMISSIONS.SETTINGS_EDIT,
        PERMISSIONS.ACCOUNTS_VIEW,
        PERMISSIONS.ACCOUNTS_CONNECT,
        PERMISSIONS.ACCOUNTS_DISCONNECT,
        PERMISSIONS.MEDIA_VIEW,
        PERMISSIONS.MEDIA_UPLOAD,
        PERMISSIONS.MEDIA_DELETE,
        PERMISSIONS.AUTOMATIONS_VIEW,
        PERMISSIONS.AUTOMATIONS_MANAGE,
        PERMISSIONS.VIDEO_VIEW,
        PERMISSIONS.VIDEO_CREATE,
        PERMISSIONS.VIDEO_RENDER,
        PERMISSIONS.DISCOVERY_VIEW,
        PERMISSIONS.DISCOVERY_MANAGE,
    ],
    MEMBER: [
        PERMISSIONS.POSTS_CREATE,
        PERMISSIONS.POSTS_EDIT,
        PERMISSIONS.POSTS_SCHEDULE,
        PERMISSIONS.ANALYTICS_VIEW,
        PERMISSIONS.TEAM_VIEW,
        PERMISSIONS.SETTINGS_VIEW,
        PERMISSIONS.ACCOUNTS_VIEW,
        PERMISSIONS.MEDIA_VIEW,
        PERMISSIONS.MEDIA_UPLOAD,
        PERMISSIONS.AUTOMATIONS_VIEW,
        PERMISSIONS.VIDEO_VIEW,
        PERMISSIONS.VIDEO_CREATE,
        PERMISSIONS.DISCOVERY_VIEW,
    ],
    VIEWER: [
        PERMISSIONS.ANALYTICS_VIEW,
        PERMISSIONS.TEAM_VIEW,
        PERMISSIONS.SETTINGS_VIEW,
        PERMISSIONS.ACCOUNTS_VIEW,
        PERMISSIONS.MEDIA_VIEW,
        PERMISSIONS.VIDEO_VIEW,
        PERMISSIONS.DISCOVERY_VIEW,
    ],
};
